services:

  backend:
    build:
      context: ./backend
    container_name: param-play-store-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@host.docker.internal:5433/nextstore
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - backend_uploads:/app/app/storage/uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
    container_name: param-play-store-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_uploads:
